name: Build and Push Image

on:
  workflow_call:
    inputs:
      dockerfile:
        description: 'Path to the Dockerfile. (default ./Dockerfile)'
        required: false
        type: string
        default: Dockerfile
      docker_context:
        description: 'Build context is the set of files located in the specified PATH or URL (default .)'
        required: false
        type: string
        default: '.'

jobs:

  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=sha,prefix=,format=long
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ${{ inputs.dockerfile  }}
          context: ${{ inputs.docker_context  }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
